repos:
  - repo: "https://github.com/pycqa/isort"
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - "--profile"
          - black
        name: isort
  - repo: "https://github.com/ambv/black"
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3
  - repo: local
    hooks:
      - id: system
        name: mypy
        entry: poetry run mypy .
        pass_filenames: false
        language: system

