language: python
python:
  - "3.7"
  - "3.8"
cache:
  directories:
    - $PIP_CACHE_DIR
env:
  global:
    - PIP_CACHE_DIR=$HOME/.cache/pip
install:
  - pip install coveralls
  - pip install poetry
  - poetry config virtualenvs.create false && poetry install -n --no-ansi
script:
  - black --check backoffice_extensions
  - isort backoffice_extensions --profile black --check
  - mypy --ignore-missing-imports backoffice_extensions
  - pytest --cov backoffice_extensions
after_success:
  - coveralls
